#ifndef EVENT_TYPE_ID_HPP_
#define EVENT_TYPE_ID_HPP_

#include "Event.hpp"

enum class EventTypeID {
    NONE = 0,
    STARTUP,

    START_RECORD,
    STOP_RECORD,
    CANCEL_RECORD,
    REMOVE_RECORD,

    START_RECORD_NOTI,
    STOP_RECORD_NOTI,
    CANCEL_RECORD_NOTI,
    REMOVE_RECORD_NOTI,
    FILTER_WAV_FILE_NOTI,

    MAX
};

#endif // EVENT_TYPE_ID_HPP_