#ifndef DEFINE_HPP_
#define DEFINE_HPP_

enum class DBusCommand {
    NONE = 0,

    // Hardware
    INITIALIZE_BLUETOOTH,
    START_SCAN_BTDEVICE,
    STOP_SCAN_BTDEVICE,
    BLUETOOTH_POWER_ON,
    BLUETOOTH_POWER_OFF,
    PAIR_BTDEVICE,
    UNPAIR_BTDEVICE,
    CONNECT_BTDEVICE,
    DISCONNECT_BTDEVICE,
    REJECT_REQUEST_CONFIRMATION,
    ACCEPT_REQUEST_CONFIRMATION,
    
    UPDATE_TEMPERATURE_NOTI,
    START_SCAN_BTDEVICE_NOTI,
    STOP_SCAN_BTDEVICE_NOTI,
    SCANNING_BTDEVICE_FOUND_NOTI,
    SCANNING_BTDEVICE_DELETE_NOTI,
    BLUETOOTH_POWER_ON_NOTI,
    BLUETOOTH_POWER_OFF_NOTI,
    BTDEVICE_PROPERTY_CHANGE_NOTI,
    PAIR_BTDEVICE_NOTI,
    UNPAIR_BTDEVICE_NOTI,
    CONNECT_BTDEVICE_NOTI,
    DISCONNECT_BTDEVICE_NOTI,
    BTDEVICE_REQUEST_CONFIRMATION_NOTI,

    PBAP_SESSION_END_NOTI,
    PBAP_PHONEBOOK_PULL_START_NOTI,
    PBAP_PHONEBOOK_PULL_NOTI,
    PBAP_PHONEBOOK_PULL_END_NOTI,
    CALL_HISTORY_PULL_START_NOTI,
    CALL_HISTORY_PULL_NOTI,
    CALL_HISTORY_PULL_END_NOTI,

    // Record
    START_RECORD,
    STOP_RECORD,
    CANCEL_RECORD,

    START_RECORD_NOTI,
    STOP_RECORD_NOTI,
    CANCEL_RECORD_NOTI,
    FILTER_WAV_FILE_NOTI,

    MAX
};

enum LogLevel {
    DEBUG = 0,
    INFO,
    WARN,
    ERROR,
    MAX
};

#endif // DEFINE_HPP_