#ifndef DEFINE_HPP_
#define DEFINE_HPP_

enum class DBusCommand {
    NONE = 0,

    // Hardware
    START_SCAN_BTDEVICE,
    STOP_SCAN_BTDEVICE,
    
    UPDATE_TEMPERATURE_NOTI,
    START_SCAN_BTDEVICE_NOTI,
    STOP_SCAN_BTDEVICE_NOTI,
    PAIRED_BTDEVICE_FOUND_NOTI,
    SCANNING_BTDEVICE_FOUND_NOTI,


    // Record
    START_RECORD,
    STOP_RECORD,
    CANCEL_RECORD,

    START_RECORD_NOTI,
    STOP_RECORD_NOTI,
    CANCEL_RECORD_NOTI,
    FILTER_WAV_FILE_NOTI,

    MAX
};

enum LogLevel {
    DEBUG = 0,
    INFO,
    WARN,
    ERROR,
    MAX
};

#endif // DEFINE_HPP_